name: crnn

gpu: ''
gpus_per_node: 1
distributed: False
multi_processing_distributed: False
workers: 0

cudnn_benchmark: True 

epochs: 1
start_epoch: 0
lr: 0.000001
warmup: 0


display_freq: 10


resume: 
save_dir: ./saved_models/

model:
  in_channels: 3
  hidden_channels: 256
  alphabet: keys/keys_demo.py
  ignore_case: False
  act: relu

  display: True 



  
dataset:
  height: 32
  width: 280

  train:
    enable: True
    path: /home/datasets/SRN
    shuffle: True
    batch_size: 2
  val:
    enable: False
    interval: 1 
    path: /home/datasets/SRN
    shuffle: False
    batch_size: 1
